"""make subreddit nullable

Revision ID: 27cfdb9ea971
Revises: ab1cfa5310b5
Create Date: 2025-01-14 22:05:40.091504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cfdb9ea971'
down_revision = 'ab1cfa5310b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audience', schema=None) as batch_op:
        batch_op.alter_column('subreddit',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audience', schema=None) as batch_op:
        batch_op.alter_column('subreddit',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
