"""add theme and topic to CuratedList

Revision ID: 3ccd8876b9ef
Revises: 40faa1d7f6c5
Create Date: 2025-01-14 21:39:08.613784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccd8876b9ef'
down_revision = '40faa1d7f6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curated_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curated_list', schema=None) as batch_op:
        batch_op.drop_column('topic')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
