"""add subreddit_list to audience

Revision ID: ab1cfa5310b5
Revises: 3ccd8876b9ef
Create Date: 2025-01-14 22:02:57.008839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1cfa5310b5'
down_revision = '3ccd8876b9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subreddit_list', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audience', schema=None) as batch_op:
        batch_op.drop_column('subreddit_list')

    # ### end Alembic commands ###
